CREATE DATABASE SHARATH;
USE SHARATH;
CREATE TABLE DRESS(BRAND_NAME VARCHAR(20),CLOTH_TYPE VARCHAR(20),CLOTH_FOR VARCHAR(20),CLOTH_PRICE FLOAT, CLOTH_COLOR VARCHAR(20));
DESC DRESS;

SELECT * FROM DRESS;
DESC DRESS;
ALTER TABLE DRESS MODIFY COLUMN CLOTH_PRICE INT;
DESC DRESS;


CREATE TABLE TEXTILE (STORE_NAME VARCHAR(20),CLOTH_FOR VARCHAR(20),AVAILABLE_CLOTH VARCHAR(20),STORE_ADRESS VARCHAR(20),PHONE_NUMBER VARCHAR(20));
DESC TEXTILE;

SELECT * FROM TEXTILE;
ALTER TABLE TEXTILE RENAME COLUMN PHONE_NUMBER TO CONTACT_NUMBER;
SELECT * FROM TEXTILE;

INSERT INTO DRESS VALUES('PUMA','COTTON','MALE',1200,'BLACK');
ALTER TABLE DRESS MODIFY COLUMN BRAND_NAME INT ;
DESC DRESS;
SELECT * FROM DRESS;
ALTER TABLE DRESS MODIFY COLUMN BRAND_NAME VARCHAR(20);
SELECT * FROM DRESS;

DELETE FROM DRESS WHERE BRAND_NAME=1;

INSERT INTO DRESS VALUES('ADDIDAS','COTTON','FEMALE',1290,'BLACK');
INSERT INTO DRESS VALUES('REEBOK','SYNTHATIC','MALE',2390,'BLACK');
INSERT INTO DRESS VALUES('MUFTI','JUTE','KID',290,'RED');
ALTER TABLE DRESS ADD SLNO INT;
SELECT * FROM DRESS;
ALTER TABLE DRESS DROP SLNO;



