CREATE DATABASE SHARATH;
USE SHARATH;
CREATE TABLE DRESS(BRAND VARCHAR(20),PRICE INT,CATAGERY VARCHAR(20),CLOTH_MATERIAL VARCHAR(20),CLOTH_COLOR VARCHAR(20));
CREATE TABLE TEXTILE(NAME VARCHAR(20),SALETYPE VARCHAR(20),TYPES_OF_DRESSES VARCHAR(20),SHOP_ADDRESS VARCHAR(20),PHONE_NUMBER BIGINT);
